Server:
  address: "10.0.20.193"
  port: 8080

RemoteStatisticServer:
  address: "10.0.20.142"
  port: 31004

RemoteMonitoringServer:
  address: "10.0.20.142"
  port: 31003

MetricsStatisticsCategory:
  - "amf"
  - "smf"
  - "udmAuthentication"
  - "sdm"
  - "ueContext"
  - "ausfAuthentication"
  - "soRProtection"
  - "subsData"
  - "SubDataProv"
  - "udsf"
  - "timer"
  - "userPlane"
  - "configuration"
  - "monitoring"
  - "NSSelection"
  - "NSSAIAvailiability"
  - "pcf"
  - "nrfProxy"
  - "nrf"
  - "eir"
  - "mme"
  - "hss"
  - "sgw"
  - "sgwlb"

MetricsMonitoringCategory:
  - "systemInfo"
  - "subscriberID"
  - "ranNodeID"
  - "AMF/nfUpdate"
  - "systemThroughput"
  - "throughputMonConf"
  - "ENodeID"
  - "accessNtwrkIdList"
  - "subscriberID"

queryParams: '{"serviceID":"slice1","tenantId":"enterprise1"}'