Server:
  address: "10.0.20.193"
  port: 8080

RemoteStatisticServer:
  address: "10.0.20.142"
  port: 31004

MetricsCategory:
  - "amf"
  - "smf"
  - "udmAuthentication"
  - "sdm"
  - "ueContext"
  - "ausfAuthentication"
  - "soRProtection"
  - "subsData"
  - "SubDataProv"
  - "udsf"
  - "timer"
  - "userPlane"
  - "configuration"
  - "monitoring"
  - "NSSelection"
  - "NSSAIAvailiability"
  - "pcf"
  - "nrfProxy"
  - "nrf"
  - "eir"
  - "mme"
  - "hss"
  - "sgw"
  - "sgwlb"

queryParams: '{"serviceID":"slice1","tenantId":"enterprise1"}'