{
 "title": "4G Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PGWC Number of EPS Bearers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "smf_EpsSessionMgmt_TotalEpsBearers",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PGWC Number of EPS Sessions ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "smf_EpsSessionMgmt_TotalEpsSessions",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PGWC Create Session Request Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(smf_SmfGtpv2Msg_CreateSessionResponseSend/smf_SmfGtpv2Msg_CreateSessionRequestRecv)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PGWC PFCP Session Establishment Success Ratio ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(smf_PFCPSessionMsg_PFCPSessionSuccess/smf_PFCPSessionMsg_PFCPSessionTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PGWC PFCP Session Modification Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(smf_PFCPSessionMsg_PFCPSessionModificationSuccess/smf_PFCPSessionMsg_PFCPSessionModificationTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PGWC PFCP Session Realase Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(smf_PFCPSessionMsg_PFCPSessionReleaseSuccess/smf_PFCPSessionMsg_PFCPSessionReleaseTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PGWU PFCP Session Establishment Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(userPlane_SessionStats_PFCPSessionCreateSuccess/userPlane_SessionStats_PFCPSessionCreateTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PGWU PFCP Session Modification Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(userPlane_SessionStats_PFCPSessionModificationSuccess/userPlane_SessionStats_PFCPSessionModificationTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PGWU PFCP Session Realase Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(userPlane_SessionStats_PFCPSessionReleaseSuccess/userPlane_SessionStats_PFCPSessionReleaseTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PGWU PFCP Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "userPlane_SessionStats_ActivePFCPSessions",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HSS Location Update Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(hss_S6aStats_ULATx/hss_S6aStats_ULRRx)*100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}