{
 "title": "5G Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "AMF Initial registration Success Ratio Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(amf_AmfNasStatsName_RegistrationInitialAccept/amf_AmfNasStatsName_RegistrationInitialRequestTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPF Active PFCP Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "userPlane_SessionStats_ActivePFCPSessions",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMF PDU Session Establishment Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(smf_PduSessionMgmt_CreatePduSessionSuccess/smf_PduSessionMgmt_CreatePduSessionTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMF Modify PDU Session Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(smf_PduSessionMgmt_ModifyPduSessionSuccess/smf_PduSessionMgmt_ModifyPduSessionTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMF PFCP Session Establishment Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(smf_PFCPSessionMsg_PFCPSessionSuccess/smf_PFCPSessionMsg_PFCPSessionTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMF PFCP Session Modification Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(smf_PFCPSessionMsg_PFCPSessionModificationSuccess/smf_PFCPSessionMsg_PFCPSessionModificationTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMF PFCP Session Release Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(smf_PFCPSessionMsg_PFCPSessionReleaseSuccess/smf_PFCPSessionMsg_PFCPSessionReleaseTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPF PFCP Session Establishment Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(userPlane_SessionStats_PFCPSessionCreateSuccess/userPlane_SessionStats_PFCPSessionCreateTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPF PFCP Session Modification Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(userPlane_SessionStats_PFCPSessionModificationSuccess/userPlane_SessionStats_PFCPSessionModificationTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPF PFCP Session Release Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(userPlane_SessionStats_PFCPSessionReleaseSuccess/userPlane_SessionStats_PFCPSessionReleaseTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDM Get SM Data Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sdm_get_GetSmDataSuccess/sdm_get_GetSmDataTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCF SM Policy Control Create Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(pcf_PcfSmf_SMPolicyControlCreateSuccess/pcf_PcfSmf_SMPolicyControlCreateTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AUSF UE Authentication Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(ausfAuthentication_authentication_UeAuthReqSuccess/ausfAuthentication_authentication_UeAuthReqTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}