{
 "title": "PGWC",
 "tags": [ "4G" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PGWC Total Eps Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "smf_EpsSessionMgmt_TotalEpsSessions",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PGWC Total Eps Bearers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "smf_EpsSessionMgmt_TotalEpsBearers",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PGWC Create Session Response Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(smf_SmfGtpv2Msg_CreateSessionResponseSend/smf_SmfGtpv2Msg_CreateSessionRequestRecv)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMF PFCP Session Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(smf_PFCPSessionMsg_PFCPSessionSuccess/smf_PFCPSessionMsg_PFCPSessionTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMF PFCP Session Modification Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(smf_PFCPSessionMsg_PFCPSessionModificationSuccess/smf_PFCPSessionMsg_PFCPSessionModificationTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMF PFCP Session Release Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(smf_PFCPSessionMsg_PFCPSessionReleaseSuccess/smf_PFCPSessionMsg_PFCPSessionReleaseTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}