{
 "title": "SMF",
 "tags": [ "5G" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "SMF Create PduSession Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(smf_PduSessionMgmt_CreatePduSessionSuccess/smf_PduSessionMgmt_CreatePduSessionTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMF Modify PduSession Sucess Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(smf_PduSessionMgmt_ModifyPduSessionSuccess/smf_PduSessionMgmt_ModifyPduSessionTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMF PFCP Session Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(smf_PFCPSessionMsg_PFCPSessionSuccess/smf_PFCPSessionMsg_PFCPSessionTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMF PFCP Session Modification Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(smf_PFCPSessionMsg_PFCPSessionModificationSuccess/smf_PFCPSessionMsg_PFCPSessionModificationTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMF PFCP Session Release Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(smf_PFCPSessionMsg_PFCPSessionReleaseSuccess/smf_PFCPSessionMsg_PFCPSessionReleaseTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}