{
 "title": "UPF",
 "tags": [
  "5G",
  "4G"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "UPF Active PFCP Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "userPlane_SessionStats_ActivePFCPSessions",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPF PFCP Session Create Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(userPlane_SessionStats_PFCPSessionCreateSuccess/userPlane_SessionStats_PFCPSessionCreateTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPF PFCP Session Modification Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(userPlane_SessionStats_PFCPSessionModificationSuccess/userPlane_SessionStats_PFCPSessionModificationTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPF PFCP Session Release Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(userPlane_SessionStats_PFCPSessionReleaseSuccess/userPlane_SessionStats_PFCPSessionReleaseTotal)*100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}